# Generated by Django 3.1.4 on 2020-12-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_auto_20201225_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('UserTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('UserType', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(help_text='Enter Username', max_length=255)),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserEmail', models.EmailField(max_length=255, unique=True)),
                ('UserMobile', models.BigIntegerField()),
                ('UserAddress', models.CharField(default='No Address', max_length=255, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('UserTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usertypemaster')),
            ],
            options={
                'ordering': ['UserName'],
            },
        ),
    ]
