# Generated by Django 3.1.4 on 2020-12-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_usermaster_usertypemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(help_text='Enter Username', max_length=255)),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserEmail', models.EmailField(max_length=255, unique=True)),
                ('UserMobile', models.BigIntegerField()),
            ],
        ),
    ]
