# Generated by Django 3.1.4 on 2020-12-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
